// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIatyN8iwe0_VZaxdqCAi0OoyDW8LXt7E',
    appId: '1:498541278767:web:14be4e0370ca29f905b8da',
    messagingSenderId: '498541278767',
    projectId: 'chick-chack-6fdf7',
    authDomain: 'chick-chack-6fdf7.firebaseapp.com',
    databaseURL: 'https://chick-chack-6fdf7-default-rtdb.firebaseio.com',
    storageBucket: 'chick-chack-6fdf7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd2BajQotsyEjkX7DPko2RN6uXOp8V49g',
    appId: '1:498541278767:android:0baf64a0da8a2cbe05b8da',
    messagingSenderId: '498541278767',
    projectId: 'chick-chack-6fdf7',
    databaseURL: 'https://chick-chack-6fdf7-default-rtdb.firebaseio.com',
    storageBucket: 'chick-chack-6fdf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmKV9mjR0ViqJiBwrqrzEorXVwB8j-r_g',
    appId: '1:498541278767:ios:81ef2a6d0cbaa3ec05b8da',
    messagingSenderId: '498541278767',
    projectId: 'chick-chack-6fdf7',
    databaseURL: 'https://chick-chack-6fdf7-default-rtdb.firebaseio.com',
    storageBucket: 'chick-chack-6fdf7.appspot.com',
    iosBundleId: 'com.example.chickChackBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmKV9mjR0ViqJiBwrqrzEorXVwB8j-r_g',
    appId: '1:498541278767:ios:81ef2a6d0cbaa3ec05b8da',
    messagingSenderId: '498541278767',
    projectId: 'chick-chack-6fdf7',
    databaseURL: 'https://chick-chack-6fdf7-default-rtdb.firebaseio.com',
    storageBucket: 'chick-chack-6fdf7.appspot.com',
    iosBundleId: 'com.example.chickChackBeta',
  );
}
